version: 1.0.{build}
branches:
  only:
    - master
    - dev

configuration: 
  - Debug
  - Release-Net45

before_build:
  - nuget restore 

build:
  verbosity: minimal

test:
  assemblies:
      - '**\*.Test.dll'

environment:
  nuget_key:
    secure: X73bZ5OhebHVJuPjUFLwmK0K3xAlTntFhW9uKGA66KKhAkBZRPm/atUUtsu04HD7