version: 1.0.{build}
branches:
  only:
    - master

configuration: 
  - Release

before_build:
  - nuget restore 

build:
  verbosity: minimal

# scripts to run after build
after_build:
  - nuget pack .\SimpleZipCode\SimpleZipCode.csproj -properties Configuration=Release

test:
  assemblies:
      - '**\*.Test.dll'

environment:
  nuget_key:
    secure: X73bZ5OhebHVJuPjUFLwmK0K3xAlTntFhW9uKGA66KKhAkBZRPm/atUUtsu04HD7